version: '3.1'
services:
  product-service:
    image: productservices:1.0
    hostname: ms.product
#    depends_on:
#      - product_db
#      - redis
    ports:
      - "8080:8080"
#    First we need create network for feign client
#    docker network create ms-services
    networks:
      - ms-services
    environment:
      DB_CONNECTION_IP: product_db
      DB_CONNECTION_PORT: 5432
      DB_NAME: product_service
      DB_CONNECTION_USERNAME: admin
      DB_CONNECTION_PASSWORD: 123456
  product_db:
    hostname: postgresql
    image: postgres:15
    networks:
      - ms-services
    restart: always
    volumes:
      - product_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    networks:
      - ms-services
    restart: always
    ports:
      - "8580:8080"
  redis:
    image: redis:latest
    container_name: redis_product
    volumes:
      - redis_data:/data
    networks:
      - ms-services
    ports:
      - "6379:6379"
networks:
  ms-services:
    external: true
volumes:
  product_db_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
