version: '3.1'
services:
  product-service:
    image: productservices:1.0
    hostname: ms.product
#    depends_on:
#      - product_db
#      - redis
    ports:
      - "8080:8080"
#    First we need create network for feign client
#    docker network create ms-services
    networks:
      - ms-services
    volumes:
      - ./logs/product-service:/opt/app/logs/product-service
    environment:
      DB_CONNECTION_IP: product_db
      DB_CONNECTION_PORT: 5432
      DB_NAME: product_service
      DB_CONNECTION_USERNAME: admin
      DB_CONNECTION_PASSWORD: 123456
  product_db:
    hostname: postgresql
    image: postgres:15
    networks:
      - ms-services
    restart: always
    volumes:
      - product_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    networks:
      - ms-services
    restart: always
    ports:
      - "8580:8080"
  redis:
    image: redis:latest
    container_name: redis_product
    volumes:
      - redis_data:/data
    networks:
      - ms-services
    ports:
      - "6379:6379"
  product_search_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: product_search_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - product_search_elk_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - ms-services
  kibana_search:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana_search
    depends_on:
      - product_search_elasticsearch
    volumes:
      - ./kibana/search/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5602:5601"
    networks:
      - ms-services
  elasticsearch_log:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch_log
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_log_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - ms-services
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/product-service:/opt/app/logs/product-service
    depends_on:
      - elasticsearch_log
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch_log:9200
    networks:
      - ms-services
  kibana_log:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana_log
    depends_on:
      - elasticsearch_log
    volumes:
      - ./kibana/log/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - ms-services
networks:
  ms-services:
    external: true
    driver: bridge
volumes:
  product_db_data:
    driver: local
  redis_data:
    driver: local
  product_search_elk_data:
    driver: local
  elasticsearch_log_data:
    driver: local