filebeat.inputs:
  - type: log
    paths:
      - /app/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "product-service-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
