filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/app/logs/product-service/*.json
    json.keys_under_root: true
    json.add_error_key: true
    json.ignore_decoding_error: true
    fields:
      service.name: product-service
    fields_under_root: true

output.elasticsearch: 
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"    # Elasticsearch istifadəçi adı
  password: "sSM*iZr*b0SOvxjC_QqP"