spring:
  application:
    name: ms.product
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
resilience4j:
  retry:
    instances:
      redisRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - com.productservice.exception.NotFoundException
management:
  health:
    elasticsearch:
      enabled: false
    rabbit:
      enabled: false
    redis:
      enabled: false
logging:
  config: classpath:logback-spring.xml
redis:
  server:
    urls: redis://redis:6379
client:
  product-service:
    url: ms.product:8080/
server:
  port: 8080
elasticsearch:
  host: product_search_elasticsearch
  port: 9200